In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle

In [2]:
# Loading the data (in this case it is CSV)

df1 =pd.read_csv( "../../CSVTables/Cross_Tb1.csv")
df2 =pd.read_csv("../../CSVTables/Cross_Tb2.csv")
df3 = pd.read_csv("../../CSVTables/Cross_Tb3.csv")
df4 = pd.read_csv("../../CSVTables/Cross_Tb4.csv")
df5 = pd.read_csv("../../CSVTables/Cross_Tb5.csv")
# df6 = pd.read_csv("../../CSVTables/Cross_Tb6.csv")
df7 = pd.read_csv("../../CSVTables/Cross_Tb7.csv")
# df8 = pd.read_csv("../../CSVTables/Cross_Tb8.csv")
# df9 = pd.read_csv("../../CSVTables/Cross_Tb9.csv")
df10 = pd.read_csv("../../CSVTables/Cross_Tb10.csv")
df11 = pd.read_csv("../../CSVTables/Cross_Tb11.csv")
df12 = pd.read_csv("../../CSVTables/Cross_Tb12.csv")
df13 = pd.read_csv("../../CSVTables/Cross_Tb13.csv")
# df14 = pd.read_csv("../../CSVTables/Cross_Tb14.csv")
df15 = pd.read_csv("../../CSVTables/Cross_Tb15.csv")
# df16 = pd.read_csv("../../CSVTables/Cross_Tb16.csv")
df17 = pd.read_csv("../../CSVTables/Cross_Tb17.csv")
# df18 = pd.read_csv("../../CSVTables/Cross_Tb18.csv")
# df19 = pd.read_csv("../../CSVTables/Cross_Tb19.csv")
df20 = pd.read_csv("../../CSVTables/Cross_Tb20.csv")
df21 = pd.read_csv("../../CSVTables/Cross_Tb21.csv")
df22 = pd.read_csv("../../CSVTables/Cross_Tb22.csv")
df23 = pd.read_csv("../../CSVTables/Cross_Tb23.csv")
# df24 = pd.read_csv("../../CSVTables/Cross_Tb24.csv")
df25 = pd.read_csv("../../CSVTables/Cross_Tb25.csv")
# df26 = pd.read_csv("../../CSVTables/Cross_Tb26.csv")
df27 = pd.read_csv("../../CSVTables/Cross_Tb27.csv")
df28 = pd.read_csv("../../CSVTables/Cross_Tb28.csv")
df29 = pd.read_csv("../../CSVTables/Cross_Tb29.csv")
df30 = pd.read_csv("../../CSVTables/EnrollmentCount_Tb.csv")
df31 = pd.read_csv("../../CSVTables/tb00.csv")

# Trial Using CSV

In [3]:
#Create list of dataframe so it is easier to iterate

list_of_df = [df1, df2, df3, df4, df5, df7, df10, df11, df12, df13, df15, df17, df20, df21, df22, df23, df25, df27, df28, df29, df30, df31]

#training code
list_of_df[2] = list_of_df[2].drop( list_of_df[2].columns[[0,1]], axis=1 )

list_of_df[2]

In [4]:
#Drop the data I don't want.
#Erase this step when finally using dataframe 


for dframe in range(0, len(list_of_df)-1 ):
    list_of_df[dframe] = list_of_df[dframe].drop( list_of_df[dframe].columns[[0,1]], axis=1 )

In [5]:
df_new = list_of_df[ (len(list_of_df)-1 )].join( list_of_df[ (len(list_of_df)-2 )] )

for dframe in range(0, len(list_of_df)-2 ):
    df_new = df_new.join( list_of_df[dframe] )

#sample joining table

df_new = df31.join(df29)
df29 = df29.drop(df29.columns[[0,1]], axis=1)
df30 = df30.drop(df30.columns[[0,1]], axis=1)

df_new = df31.join(df29)
df_new = df_new.join(df30)

In [6]:
df_new = df_new.dropna(how = 'any')

print( df_new.head() )
print(len(df_new.index) )

         NCTId OverallStatus  Phase_1  Phase_2  Phase_3  Phase_4  Phase_n/a  \
0  NCT00000102     Completed        1        1        0        0          0
1  NCT00000104     Completed        0        0        0        0          1
2  NCT00000105    Terminated        0        0        0        0          1
3  NCT00000106         Other        0        0        0        0          1
4  NCT00000107     Completed        0        0        0        0          1

   51-100  101-200  201-500  ...  tb25_No  tb25_Yes  \
0       0        1        0  ...        0         0
1       0        0        0  ...        0         0
2       0        0        0  ...        0         0
3       0        0        0  ...        0         0
4       0        0        0  ...        0         0

   tb27_NonProbabilitySample  tb27_ProbabilitySample  tb28_Adult  tb28_Child  \
0                          0                       0           1           1
1                          0                       0           1           1
2                          0                       1           1           0
3                          0                       0           1           0
4                          0                       0           1           1

   tb28_OlderAdult  tb29_ExpandedAccess  tb29_Interventional  \
0                0                    0                    1
1                1                    0                    0
2                1                    0                    0
3                1                    0                    1
4                0                    0                    0

   tb29_Observational
0                   0
1                   1
2                   1
3                   0
4                   1

[5 rows x 190 columns]
111592

In [7]:
## 2. Regression Machine learning using sample data

In [8]:
### 2.a Prepping: extract the name of the column

key_name =  df_new.keys()
X_name = key_name[7:]

X_name

Index(['51-100', '101-200', '201-500', '501-1000', '1001-10000', '10000plus',
       'tb1_Biological', 'tb1_CombinationProduct', 'tb1_Device',
       'tb1_DiagnosticTest',
       ...
       'tb25_No', 'tb25_Yes', 'tb27_NonProbabilitySample',
       'tb27_ProbabilitySample', 'tb28_Adult', 'tb28_Child', 'tb28_OlderAdult',
       'tb29_ExpandedAccess', 'tb29_Interventional', 'tb29_Observational'],
      dtype='object', length=183)

In [9]:
### 2.b Select the data we want.
### In this case, we only pick Phase 2, and the Overall Status has to be either

df_filtered = df_new[ df_new["Phase_2"] == 1 ]
df_filtered = df_filtered[ (df_filtered["OverallStatus"] == "Completed") | (df_filtered ["OverallStatus"] =="Terminated")  ]

# print(df_filtered.describe() )

#drop null values
# df_filtered = df_filtered.dropna(how = 'any')

print(len(df_filtered.index ))

22506

In [10]:
df_filtered.groupby("OverallStatus").count()

,NCTId,Phase_1,Phase_2,Phase_3,Phase_4,Phase_n/a,51-100,101-200,201-500,501-1000,...,tb25_No,tb25_Yes,tb27_NonProbabilitySample,tb27_ProbabilitySample,tb28_Adult,tb28_Child,tb28_OlderAdult,tb29_ExpandedAccess,tb29_Interventional,tb29_Observational
OverallStatus,,,,,,,,,,,,,,,,,,,,,
Completed,17503,17503,17503,17503,17503,17503,17503,17503,17503,17503,...,17503,17503,17503,17503,17503,17503,17503,17503,17503,17503
Terminated,5003,5003,5003,5003,5003,5003,5003,5003,5003,5003,...,5003,5003,5003,5003,5003,5003,5003,5003,5003,5003

In [11]:
### 2.c Assign data to X and Y

X = df_filtered[X_name]
y = df_filtered["OverallStatus"]
print(X.shape , y.shape)

(22506, 183) (22506,)

In [12]:
### 2.d Use train_test_split to create training and testing data

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
X_train

,51-100,101-200,201-500,501-1000,1001-10000,10000plus,tb1_Biological,tb1_CombinationProduct,tb1_Device,tb1_DiagnosticTest,...,tb25_No,tb25_Yes,tb27_NonProbabilitySample,tb27_ProbabilitySample,tb28_Adult,tb28_Child,tb28_OlderAdult,tb29_ExpandedAccess,tb29_Interventional,tb29_Observational
15344,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
15428,1,0,0,0,0,0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,0,1,0,1,0
9570,0,0,0,0,0,0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,0,1,0,1,0
53727,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
82782,0,0,1,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84115,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
49527,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
65882,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
34913,0,1,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
6546,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,1,0

In [14]:
# Create the model using LinearRegression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
# Fit the model to the training data and calculate the scores for the training and testing data

### BEGIN SOLUTION
classifier.fit(X_train, y_train)

### END SOLUTION 

print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7826293026838083
Testing Data Score: 0.7753687577750134

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [16]:
predictions = classifier.predict(X_test)
print(f"First 30 Predictions:   {predictions[:30]}")
print(f"First 30 Actual labels: {y_test[:30].tolist()}")

First 30 Predictions:   ['Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed']
First 30 Actual labels: ['Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Terminated', 'Completed', 'Terminated', 'Completed', 'Completed', 'Terminated', 'Completed', 'Completed', 'Completed', 'Completed', 'Terminated', 'Completed', 'Terminated', 'Terminated', 'Completed', 'Terminated', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Terminated']

In [17]:
np.unique(predictions)

array(['Completed', 'Terminated'], dtype=object)

In [18]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

      Prediction      Actual
0      Completed   Completed
1      Completed   Completed
2      Completed   Completed
3      Completed   Completed
4      Completed   Completed
...          ...         ...
5622   Completed   Completed
5623   Completed  Terminated
5624   Completed   Completed
5625   Completed   Completed
5626  Terminated   Completed

[5627 rows x 2 columns]

In [19]:
#4. save the regression model
filename = "clinical_trial.sav"
pickle.dump(classifier , open(filename, 'wb'))

In [20]:
### 5. Try applying the model into other non-concluded trial.

### 5.a Predict using other data

df_other_trial = df_new[ df_new["Phase_2"] == 1 ]
df_other_trial = df_other_trial[ (df_other_trial["OverallStatus"] != "Completed") & (df_other_trial["OverallStatus"] != "Terminated") ]
df_other_trial

,NCTId,OverallStatus,Phase_1,Phase_2,Phase_3,Phase_4,Phase_n/a,51-100,101-200,201-500,...,tb25_No,tb25_Yes,tb27_NonProbabilitySample,tb27_ProbabilitySample,tb28_Adult,tb28_Child,tb28_OlderAdult,tb29_ExpandedAccess,tb29_Interventional,tb29_Observational
11,NCT00000119,Other,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,0
955,NCT00001337,Ongoing,0,1,0,0,0,0,0,0,...,0,0,0,0,1,1,1,0,1,0
991,NCT00001379,Ongoing,0,1,0,0,0,0,0,0,...,0,0,0,0,1,1,1,0,1,0
1077,NCT00001481,Ongoing,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1105,NCT00001521,Ongoing,0,1,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111553,NCT03424005,Ongoing,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,0
111578,NCT03424850,Ongoing,1,1,0,0,0,0,1,0,...,0,0,0,0,1,0,1,0,1,0
111582,NCT03425006,Ongoing,0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,1,0,1,0
111584,NCT03425097,Ongoing,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,0
111589,NCT03425279,Ongoing,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,0

In [21]:
### 5.b Assign data to X and Y

X_other = df_other_trial[X_name]
y_other = df_other_trial["OverallStatus"]
X_other

,51-100,101-200,201-500,501-1000,1001-10000,10000plus,tb1_Biological,tb1_CombinationProduct,tb1_Device,tb1_DiagnosticTest,...,tb25_No,tb25_Yes,tb27_NonProbabilitySample,tb27_ProbabilitySample,tb28_Adult,tb28_Child,tb28_OlderAdult,tb29_ExpandedAccess,tb29_Interventional,tb29_Observational
11,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
955,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,1,0,1,0
991,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,1,0,1,0
1077,0,0,0,1,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1105,0,0,0,0,0,1,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111553,0,0,0,0,0,0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,0,1,0,1,0
111578,0,1,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
111582,0,0,1,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
111584,0,0,0,1,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
111589,0,0,0,1,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0

In [22]:
X_other.head()

,51-100,101-200,201-500,501-1000,1001-10000,10000plus,tb1_Biological,tb1_CombinationProduct,tb1_Device,tb1_DiagnosticTest,...,tb25_No,tb25_Yes,tb27_NonProbabilitySample,tb27_ProbabilitySample,tb28_Adult,tb28_Child,tb28_OlderAdult,tb29_ExpandedAccess,tb29_Interventional,tb29_Observational
11,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,1,0,1,0
955,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,1,0,1,0
991,0,0,0,0,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,1,0,1,0
1077,0,0,0,1,0,0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1105,0,0,0,0,0,1,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,1,0

In [23]:
predictions_other = classifier.predict(X_other)
print(f"First 30 Predictions:   {predictions[:30]}")

First 30 Predictions:   ['Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed'
 'Completed' 'Completed' 'Completed' 'Completed' 'Completed' 'Completed']

In [24]:
other_result = pd.DataFrame({"Prediction": predictions_other }).reset_index(drop=True)
other_result["value_count"] = 1



other_result

      Prediction  value_count
0      Completed            1
1      Completed            1
2      Completed            1
3      Completed            1
4      Completed            1
...          ...          ...
5073   Completed            1
5074  Terminated            1
5075  Terminated            1
5076   Completed            1
5077   Completed            1

[5078 rows x 2 columns]

In [25]:
other_NCTId = df_other_trial["NCTId"].values
len(other_NCTId)

5078

In [26]:
other_NCTId = df_other_trial["NCTId"].values

other_result = pd.DataFrame({"Prediction": predictions_other}).reset_index(drop=True)
other_result["value_count"] = 1

other_result ["NCTId"] = other_NCTId

other_result.to_csv('LogisticReg_Result.csv')

In [27]:
other_result.groupby("Prediction").sum()

            value_count
Prediction
Completed          4477
Terminated          601

In [28]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["Completed", "Terminated"]))

              precision    recall  f1-score   support

   Completed       0.78      0.98      0.87      4361
  Terminated       0.51      0.07      0.12      1266

    accuracy                           0.78      5627
   macro avg       0.64      0.52      0.50      5627
weighted avg       0.72      0.78      0.70      5627