In [1]:
# Dependencies
import json
import os
import pandas as pd

In [2]:
with open('json2/field_usa0_part_4.json') as jsonfile:
    study_json = json.load(jsonfile)

In [3]:
# Load JSON

part4=[ 'NCTId' , 'ConditionAncestorTerm' , 'ConditionBrowseBranchAbbrev' , 'ConditionBrowseBranchName' , 'ConditionBrowseLeafAsFound' , 'ConditionBrowseLeafId' , 'ConditionBrowseLeafName' , 'ConditionBrowseLeafRelevance' , 'ConditionMeshId' , 'ConditionMeshTerm' , 'DelayedPosting' , 'DesignAllocation' , 'DesignInterventionModel' , 'DesignInterventionModelDescription' , 'DesignMasking' , 'DesignMaskingDescription' , 'DesignObservationalModel' , 'DesignPrimaryPurpose' , 'DesignTimePerspective' , 'DesignWhoMasked ' ]

In [4]:
#Joining USA0 and USA1

# all fields of part 1
NCTId=[]

BaselineMeasureDispersionType = []

BaselineMeasureParamType = []

In [5]:
#Extract All of Part1

rank_number = len(study_json["StudyFieldsResponse"]["StudyFields"])
fields_number =len( study_json["StudyFieldsResponse"]["StudyFields"][0])
print (rank_number)

1000

In [6]:
#Extract All of Part1

rank_number = len(study_json["StudyFieldsResponse"]["StudyFields"])
fields_number =len( study_json["StudyFieldsResponse"]["StudyFields"][0])
print (rank_number)

#Extracting from multiple files

for trial_batch in range (0,2):

    trial_batch = 0
    trial_path="json2/field_usa"+str(trial_batch)+"_part_4.json"

    with open(trial_path) as jsonfile:
        study_json = json.load(jsonfile)

    rank_number = len(study_json["StudyFieldsResponse"]["StudyFields"])
    fields_number =len( study_json["StudyFieldsResponse"]["StudyFields"][0])

    for x in range (0,rank_number):

    #     if AgreementOtherDetails.append(study_json['StudyFieldsResponse']['StudyFields'][x]['AgreementOtherDetails']='':
    #         AgreementOtherDetails.append(0)
    #     else:
    #         AgreementOtherDetails.append(study_json['StudyFieldsResponse']['StudyFields'][x]['AgreementOtherDetails'][0]

        study_content= study_json['StudyFieldsResponse']['StudyFields'][x]

        if len(study_content['NCTId']) ==0 :
            NCTId.append(0)
        if len(study_content['NCTId']) ==1 :
            NCTId.append(study_content['NCTId'][0]) 
        elif len(study_content['NCTId']) > 1:
            NCTId.append(study_content['NCTId'])  
            
        if len(study_content['BaselineMeasureDispersionType']) ==0 :
            BaselineMeasureDispersionType.append(0)
        if len(study_content['BaselineMeasureDispersionType']) ==1 :
            BaselineMeasureDispersionType.append(study_content['BaselineMeasureDispersionType'][0]) 
        elif len(study_content['BaselineMeasureDispersionType']) > 1:
            BaselineMeasureDispersionType.append(study_content['BaselineMeasureDispersionType'])  

        if len(study_content['BaselineMeasureParamType']) ==0 :
            BaselineMeasureParamType.append(0)
        if len(study_content['BaselineMeasureParamType']) ==1 :
            BaselineMeasureParamType.append(study_content['BaselineMeasureParamType'][0]) 
        elif len(study_content['BaselineMeasureParamType']) > 1:
            BaselineMeasureParamType.append(study_content['BaselineMeasureParamType'])

1000

In [7]:
len(NCTId)

2000

In [8]:
#Create Dataframe from list
dict1 = { part1[0]:NCTId,

part1[1]:BaselineMeasureDispersionType,

part1[2]:BaselineMeasureParamType}

df1 = pd.DataFrame(dict1)

#df1.to_csv('fields_all_part1.csv')

In [9]:
df1

,NCTId,BaselineMeasureDispersionType,BaselineMeasureParamType
0,NCT04371159,0,0
1,NCT04474496,0,0
2,NCT02801266,0,0
3,NCT01599390,0,0
4,NCT00312702,Standard Deviation,"[Mean, Count of Participants, Count of Partici..."
...,...,...,...
1995,NCT00542477,0,0
1996,NCT00529685,0,0
1997,NCT00506220,0,0
1998,NCT00448812,0,0
1999,NCT00350259,0,0

In [11]:
def explodeTable(df_name, column_name):
    tb = df_name[['NCTId', column_name]].copy()
    explode_tb = tb.explode(column_name)
    explode_tb = explode_tb.replace(0, "-")
    explode_tb = explode_tb.sort_values(by=[column_name], ascending=False)
    fr = len(explode_tb) - explode_tb[column_name].str.contains('-', na=False).sum()
    print('feature_row', fr)
    feature_tb = explode_tb.head(fr)
    #.rename(columns={column_name:'features'})

    return feature_tb

In [12]:
tb3= explodeTable(df1, 'BaselineMeasureDispersionType')
tb3

feature_row 90

            NCTId BaselineMeasureDispersionType
1095  NCT02207569            Standard Deviation
131   NCT02939131            Standard Deviation
112   NCT00796315            Standard Deviation
116   NCT00730964            Standard Deviation
1112  NCT00796315            Standard Deviation
...           ...                           ...
22    NCT00928694                    Full Range
22    NCT00928694                    Full Range
1022  NCT00928694                    Full Range
1022  NCT00928694                    Full Range
1022  NCT00928694                    Full Range

[90 rows x 2 columns]

tb1['feature'] = tb1['ArmGroupInterventionName'].str.split(' ').str[0]
tb1 = tb1.drop(['ArmGroupInterventionName'], axis=1)
tb1 = tb1.rename(columns={'feature':'ArmGroupInterventionName'})
tb1

In [14]:
# Creating cross table
Cross_Tb3 = pd.crosstab(index=tb3['NCTId'], columns = tb3['BaselineMeasureDispersionType'])
Cross_Tb3.to_csv('Cross_Tb3.csv')
Cross_Tb3

BaselineMeasureDispersionType  Full Range  Standard Deviation
NCTId
NCT00312663                             0                   2
NCT00312702                             0                   2
NCT00351741                             0                   2
NCT00601835                             0                   2
NCT00724867                             0                   2
NCT00730964                             0                   2
NCT00796315                             0                   2
NCT00875641                             0                   2
NCT00928694                             6                   0
NCT01087905                             0                   2
NCT01112917                             0                   2
NCT01154296                             0                   8
NCT01256164                             0                   2
NCT01369030                             0                   2
NCT01568424                            12                   2
NCT01965561                             4                   0
NCT02128542                             0                   4
NCT02207569                             0                   2
NCT02395536                             0                   4
NCT02746809                             0                   2
NCT02939131                             0                  20
NCT03973905                             0                   2

In [15]:
#Creating 0 and 1 matrix table
Cross_Tb3[Cross_Tb3>1]=1
Cross_Tb3.reset_index()
Cross_Tb3.to_csv('Cross_Tb3_1.csv')
Cross_Tb3

BaselineMeasureDispersionType  Full Range  Standard Deviation
NCTId
NCT00312663                             0                   1
NCT00312702                             0                   1
NCT00351741                             0                   1
NCT00601835                             0                   1
NCT00724867                             0                   1
NCT00730964                             0                   1
NCT00796315                             0                   1
NCT00875641                             0                   1
NCT00928694                             1                   0
NCT01087905                             0                   1
NCT01112917                             0                   1
NCT01154296                             0                   1
NCT01256164                             0                   1
NCT01369030                             0                   1
NCT01568424                             1                   1
NCT01965561                             1                   0
NCT02128542                             0                   1
NCT02207569                             0                   1
NCT02395536                             0                   1
NCT02746809                             0                   1
NCT02939131                             0                   1
NCT03973905                             0                   1

In [16]:
tb4= explodeTable(df1, 'BaselineMeasureParamType')
tb4

feature_row 280

            NCTId BaselineMeasureParamType
1083  NCT02128542                   Number
135   NCT01369030                   Number
1068  NCT01154296                   Number
1068  NCT01154296                   Number
1041  NCT02395536                   Number
...           ...                      ...
1073  NCT00601835    Count of Participants
1154  NCT01112917    Count of Participants
127   NCT01256164    Count of Participants
1154  NCT01112917    Count of Participants
41    NCT02395536    Count of Participants

[280 rows x 2 columns]

In [17]:
Cross_Tb4 = pd.crosstab(index=tb4['NCTId'], columns = tb4['BaselineMeasureParamType'])
Cross_Tb4.to_csv('Cross_Tb4.csv')
Cross_Tb4

BaselineMeasureParamType,Count of Participants,Least Squares Mean,Mean,Median,Number
NCTId,,,,,
NCT00312663,4,0,2,0,2
NCT00312702,6,0,2,0,2
NCT00351741,4,0,2,0,2
NCT00601835,4,0,2,0,2
NCT00724867,2,0,2,0,2
NCT00730964,2,0,2,0,4
NCT00796315,2,0,2,0,4
NCT00875641,4,0,2,0,0
NCT00928694,2,0,6,0,0
NCT01028300,4,0,0,0,2
NCT01087905,4,0,2,0,2
NCT01112917,6,0,2,0,2
NCT01154296,0,8,0,0,26
NCT01256164,4,0,2,0,2
NCT01369030,2,0,2,0,4
NCT01568424,2,0,2,12,0
NCT01965561,2,0,4,0,0
NCT02128542,2,0,4,0,12
NCT02207569,2,0,2,0,2
NCT02395536,24,0,4,0,2
NCT02746809,6,0,2,0,0
NCT02813577,6,0,0,0,2
NCT02939131,12,0,20,0,0
NCT02959827,6,0,0,0,0
NCT03973905,4,0,2,0,0

In [ ]:
#Creating 0 and 1 matrix table
Cross_Tb4[Cross_Tb4>1]=1
Cross_Tb4.reset_index()
Cross_Tb4.to_csv('Cross_Tb4_1.csv')
Cross_Tb4

In [ ]:
feature_table = pd.DataFrame()
feature_table = feature_table.append(feature_tb1, ignore_index = True)
feature_table = feature_table.append(feature_tb2, ignore_index = True)
feature_table

In [ ]:
Cross_Tb = pd.crosstab(index=feature_table['NCTId'], columns = feature_table['features'])
Cross_Tb